use super::vault::{VAULT_ACCOUNT, VaultCache, VaultIo};
use super::*;
use std::collections::BTreeMap;
use std::sync::{Arc, Barrier, Mutex};

// Hand-authored wire fixtures. None is generated by the codec being tested.
const V1_ALL: &[u8] = b"RTRCTV1\x070123456789abcdef0123456789abcdef********************************||||||||||||||||||||||||||||||||";

fn fixture_v2() -> Vec<u8> {
    // Names use one-byte lengths; values use one-byte lengths (always 32).
    [
        &b"RTRCTV2\x04"[..],
        b"\x20telegram/legacy-profile/api-hash\x200123456789abcdef0123456789abcdef",
        b"\x2atelegram/legacy-profile/tdlib-database-key\x20********************************",
        b"\x15retract/job-store-key\x20||||||||||||||||||||||||||||||||",
        b"\x19retract/content-index-key\x20CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    ]
    .concat()
}

#[test]
fn keychain_vault_reads_frozen_v1_without_changing_its_encoding() {
    let vault = decode_secret_vault(V1_ALL).unwrap();
    assert_eq!(
        vault.telegram_api_hash.as_deref(),
        Some("0123456789abcdef0123456789abcdef")
    );
    assert_eq!(vault.tdlib_database_key, Some([b'*'; 32]));
    assert_eq!(vault.job_store_key, Some([b'|'; 32]));
    assert_eq!(encode_secret_vault(&vault).unwrap().as_slice(), V1_ALL);
}

#[test]
fn keychain_vault_reads_namespaced_v2_and_retains_telegram_secrets() {
    let encoded = fixture_v2();
    let vault = decode_secret_vault(&encoded).expect("namespaced v2 vault must load");
    assert_eq!(
        vault.telegram_api_hash.as_deref(),
        Some("0123456789abcdef0123456789abcdef")
    );
    assert_eq!(vault.tdlib_database_key, Some([b'*'; 32]));
    assert_eq!(vault.job_store_key, Some([b'|'; 32]));
    assert_eq!(encode_secret_vault(&vault).unwrap().as_slice(), encoded);
}

#[derive(Default)]
struct MemoryStorage {
    items: BTreeMap<String, Vec<u8>>,
    reads: usize,
    writes: usize,
    deny_reads: bool,
    reject_write: bool,
    fail_readback: bool,
    corrupt_readback: bool,
    commit_then_error: bool,
    next_read_corrupt: bool,
    unavailable_account: Option<String>,
}

#[derive(Clone, Default)]
struct MemoryVaultIo(Arc<Mutex<MemoryStorage>>);

impl MemoryVaultIo {
    fn from_bytes(bytes: &[u8]) -> Self {
        let io = Self::default();
        io.0.lock()
            .unwrap()
            .items
            .insert(VAULT_ACCOUNT.into(), bytes.to_vec());
        io
    }

    fn persisted(&self) -> Option<Vec<u8>> {
        self.0.lock().unwrap().items.get(VAULT_ACCOUNT).cloned()
    }

    fn read_count(&self) -> usize {
        self.0.lock().unwrap().reads
    }
    fn write_count(&self) -> usize {
        self.0.lock().unwrap().writes
    }
}

fn denied() -> AppError {
    AppError::SecureStore("macOS Keychain: synthetic access denied".into())
}

impl VaultIo for MemoryVaultIo {
    fn read(&mut self, account: &str) -> Result<Option<Zeroizing<Vec<u8>>>, AppError> {
        let mut storage = self.0.lock().unwrap();
        storage.reads += 1;
        if storage.deny_reads {
            return Err(denied());
        }
        if storage.unavailable_account.as_deref() == Some(account) {
            return Err(AppError::SecureStore(
                "macOS Keychain: synthetic unavailable vault".into(),
            ));
        }
        if std::mem::take(&mut storage.next_read_corrupt) {
            return Ok(Some(Zeroizing::new(b"RTRCTV9".to_vec())));
        }
        Ok(storage.items.get(account).cloned().map(Zeroizing::new))
    }

    fn write(&mut self, bytes: &[u8]) -> Result<(), AppError> {
        let mut storage = self.0.lock().unwrap();
        if storage.reject_write {
            return Err(denied());
        }
        storage.writes += 1;
        storage.items.insert(VAULT_ACCOUNT.into(), bytes.to_vec());
        if storage.fail_readback {
            storage.deny_reads = true;
        }
        if storage.corrupt_readback {
            storage.next_read_corrupt = true;
        }
        if std::mem::take(&mut storage.commit_then_error) {
            return Err(denied());
        }
        Ok(())
    }
}

fn assert_telegram_secrets(cache: &VaultCache, io: &mut MemoryVaultIo) {
    assert_eq!(
        cache.api_hash(io).unwrap().as_deref().map(String::as_str),
        Some("0123456789abcdef0123456789abcdef")
    );
    assert_eq!(cache.named_key(io, "tdlib-database").unwrap(), [b'*'; 32]);
    assert_eq!(
        cache.named_key(io, "encrypted-job-store").unwrap(),
        [b'|'; 32]
    );
}

fn persisted_content_key(io: &MemoryVaultIo) -> [u8; 32] {
    decode_secret_vault(&io.persisted().unwrap())
        .unwrap()
        .content_index_key
        .unwrap()
}

#[test]
fn keychain_vault_archive_use_is_lazy_and_reuses_one_verified_key() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    assert_telegram_secrets(&cache, &mut io);
    assert_eq!(io.write_count(), 0);
    let first = cache.archive_key(&mut io).unwrap();
    let reads = io.read_count();
    let second = cache.archive_key(&mut io).unwrap();
    assert_eq!(first, second);
    assert_eq!(first, persisted_content_key(&io));
    assert_eq!(io.write_count(), 1);
    assert_eq!(io.read_count(), reads);
    let reopened = VaultCache::default();
    assert_telegram_secrets(&reopened, &mut io);
    assert_eq!(reopened.archive_key(&mut io).unwrap(), first);
    assert_eq!(io.write_count(), 1);
}

#[test]
fn keychain_vault_rejected_archive_write_preserves_cached_telegram_secrets() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    assert_telegram_secrets(&cache, &mut io);
    io.0.lock().unwrap().reject_write = true;
    assert!(cache.archive_key(&mut io).is_err());
    assert_eq!(io.persisted().unwrap(), V1_ALL);
    let reads = io.read_count();
    assert_telegram_secrets(&cache, &mut io);
    assert_eq!(io.read_count(), reads);
    io.0.lock().unwrap().reject_write = false;
    let key = cache.archive_key(&mut io).unwrap();
    assert_eq!(key, persisted_content_key(&io));
    assert_eq!(io.write_count(), 1);
}

#[test]
fn keychain_vault_uncertain_write_blocks_api_edit_until_reread_then_retains_key() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    assert_telegram_secrets(&cache, &mut io);
    io.0.lock().unwrap().fail_readback = true;
    assert!(cache.archive_key(&mut io).is_err());
    let persisted = io.persisted().unwrap();
    let key = persisted_content_key(&io);
    let reads = io.read_count();
    assert_telegram_secrets(&cache, &mut io);
    assert_eq!(io.read_count(), reads);
    assert!(
        cache
            .save_api_hash(&mut io, "abcdef0123456789abcdef0123456789")
            .is_err()
    );
    assert!(cache.archive_key(&mut io).is_err());
    assert_eq!(io.write_count(), 1);
    assert_eq!(io.persisted().unwrap(), persisted);
    {
        let mut storage = io.0.lock().unwrap();
        storage.deny_reads = false;
        storage.fail_readback = false;
    }
    cache
        .save_api_hash(&mut io, "abcdef0123456789abcdef0123456789")
        .unwrap();
    assert_eq!(cache.archive_key(&mut io).unwrap(), key);
    assert_eq!(persisted_content_key(&io), key);
    assert_eq!(io.write_count(), 2);
    assert_eq!(
        cache.api_hash(&mut io).unwrap().unwrap().as_str(),
        "abcdef0123456789abcdef0123456789"
    );
}

#[test]
fn keychain_vault_write_error_after_commit_recovers_persisted_key() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    io.0.lock().unwrap().commit_then_error = true;
    assert!(cache.archive_key(&mut io).is_err());
    let key = persisted_content_key(&io);
    assert_eq!(cache.archive_key(&mut io).unwrap(), key);
    assert_eq!(io.write_count(), 1);
}

#[test]
fn keychain_vault_malformed_readback_does_not_publish_candidate() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    io.0.lock().unwrap().corrupt_readback = true;
    assert!(cache.archive_key(&mut io).is_err());
    let key = persisted_content_key(&io);
    let reads = io.read_count();
    assert_telegram_secrets(&cache, &mut io);
    assert_eq!(io.read_count(), reads);
    assert_eq!(cache.archive_key(&mut io).unwrap(), key);
    assert_eq!(io.write_count(), 1);
    assert!(io.read_count() > reads);
}

#[test]
fn keychain_vault_startup_denial_is_cached_without_prompt_loops() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    io.0.lock().unwrap().deny_reads = true;
    assert!(cache.archive_key(&mut io).is_err());
    io.0.lock().unwrap().deny_reads = false;
    assert!(cache.api_hash(&mut io).is_err());
    assert!(cache.named_key(&mut io, "tdlib-database").is_err());
    assert!(
        cache
            .save_api_hash(&mut io, "0123456789abcdef0123456789abcdef")
            .is_err()
    );
    assert_eq!(io.read_count(), 1);
    assert_eq!(io.write_count(), 0);
}

#[test]
fn keychain_vault_unknown_existing_input_is_preserved_without_migration() {
    for bytes in [
        b"RTRCTV9\x00".to_vec(),
        [fixture_v2(), b"unknown".to_vec()].concat(),
    ] {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::from_bytes(&bytes);
        assert!(cache.archive_key(&mut io).is_err());
        assert!(
            cache
                .save_api_hash(&mut io, "0123456789abcdef0123456789abcdef")
                .is_err()
        );
        assert_eq!(io.persisted().unwrap(), bytes);
        assert_eq!(io.read_count(), 1);
        assert_eq!(io.write_count(), 0);
    }
}

#[test]
fn keychain_vault_concurrent_archive_requests_share_a_single_commit() {
    let cache = Arc::new(VaultCache::default());
    let io = MemoryVaultIo::from_bytes(V1_ALL);
    let barrier = Arc::new(Barrier::new(8));
    let requests: Vec<_> = (0..8)
        .map(|_| {
            let cache = Arc::clone(&cache);
            let mut io = io.clone();
            let barrier = Arc::clone(&barrier);
            std::thread::spawn(move || {
                barrier.wait();
                cache.archive_key(&mut io).unwrap()
            })
        })
        .collect();
    let keys: Vec<_> = requests
        .into_iter()
        .map(|request| request.join().unwrap())
        .collect();
    assert!(keys.iter().all(|key| *key == persisted_content_key(&io)));
    assert_eq!(io.write_count(), 1);
}

#[test]
fn keychain_vault_all_legacy_item_combinations_migrate_without_changing_keys() {
    for flags in 0..8 {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::default();
        {
            let mut storage = io.0.lock().unwrap();
            if flags & 1 != 0 {
                storage.items.insert(
                    "telegram-api-hash".into(),
                    b"0123456789abcdef0123456789abcdef".to_vec(),
                );
            }
            if flags & 2 != 0 {
                storage
                    .items
                    .insert("tdlib-database".into(), vec![b'*'; 32]);
            }
            if flags & 4 != 0 {
                storage
                    .items
                    .insert("encrypted-job-store".into(), vec![b'|'; 32]);
            }
        }
        let hash = cache.api_hash(&mut io).unwrap();
        assert_eq!(
            hash.as_deref().map(String::as_str),
            if flags & 1 != 0 {
                Some("0123456789abcdef0123456789abcdef")
            } else {
                None
            }
        );
        assert_eq!(io.write_count(), usize::from(flags != 0));
        if flags != 0 {
            let original = io.persisted().unwrap();
            assert!(original.starts_with(b"RTRCTV1"));
            assert_eq!(original[7], flags);
        }
        let key = cache.archive_key(&mut io).unwrap();
        let decoded = decode_secret_vault(&io.persisted().unwrap()).unwrap();
        assert_eq!(decoded.content_index_key, Some(key));
        assert_eq!(
            decoded.tdlib_database_key,
            if flags & 2 != 0 {
                Some([b'*'; 32])
            } else {
                None
            }
        );
        assert_eq!(
            decoded.job_store_key,
            if flags & 4 != 0 {
                Some([b'|'; 32])
            } else {
                None
            }
        );
        assert_eq!(
            io.0.lock().unwrap().items.len(),
            flags.count_ones() as usize + 1
        );
    }
}

#[test]
fn keychain_vault_rejects_duplicate_unknown_malformed_and_unbounded_v2_entries() {
    let original = fixture_v2();
    let mut cases: Vec<Vec<u8>> = (0..original.len())
        .map(|end| original[..end].to_vec())
        .collect();
    cases.push([original.clone(), vec![0]].concat());
    let mut unknown_version = original.clone();
    unknown_version[6] = b'9';
    cases.push(unknown_version);
    let mut too_many = original.clone();
    too_many[7] = 5;
    cases.push(too_many);
    let mut unbounded_name = original.clone();
    unbounded_name[8] = 255;
    cases.push(unbounded_name);
    let mut unknown_name = original.clone();
    unknown_name[9] = b'x';
    cases.push(unknown_name);
    let mut wrong_value_len = original.clone();
    wrong_value_len[41] = 31;
    cases.push(wrong_value_len);
    let mut invalid_hash = original.clone();
    invalid_hash[42] = b'z';
    cases.push(invalid_hash);
    let mut invalid_utf8 = original.clone();
    invalid_utf8[42] = 255;
    cases.push(invalid_utf8);
    cases.push([&b"RTRCTV2\x02"[..], &original[8..74], &original[8..74]].concat());
    for malformed in cases {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::from_bytes(&malformed);
        assert!(cache.archive_key(&mut io).is_err());
        assert_eq!(io.persisted().unwrap(), malformed);
        assert_eq!(io.write_count(), 0);
    }
}

#[test]
fn keychain_vault_accepts_reordered_known_entries_without_changing_values() {
    let bytes = fixture_v2();
    let reordered = [
        &bytes[..8],
        &bytes[205..264],
        &bytes[150..205],
        &bytes[74..150],
        &bytes[8..74],
    ]
    .concat();
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(&reordered);
    assert_telegram_secrets(&cache, &mut io);
    assert_eq!(cache.archive_key(&mut io).unwrap(), [b'C'; 32]);
    assert_eq!(io.persisted().unwrap(), reordered);
    assert_eq!(io.write_count(), 0);
}

#[test]
fn keychain_vault_telegram_only_edits_keep_v1_and_upgraded_edits_keep_v2() {
    for original in [b"RTRCTV1\x00".as_slice(), b"RTRCTV2\x00".as_slice()] {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::from_bytes(original);
        cache
            .save_api_hash(&mut io, "0123456789abcdef0123456789abcdef")
            .unwrap();
        let tdlib = cache.named_key(&mut io, "tdlib-database").unwrap();
        let job = cache.named_key(&mut io, "encrypted-job-store").unwrap();
        let persisted = io.persisted().unwrap();
        assert_eq!(&persisted[..7], &original[..7]);
        assert!(
            decode_secret_vault(&persisted)
                .unwrap()
                .content_index_key
                .is_none()
        );
        let reopened = VaultCache::default();
        assert_eq!(
            reopened.named_key(&mut io, "tdlib-database").unwrap(),
            tdlib
        );
        assert_eq!(
            reopened.named_key(&mut io, "encrypted-job-store").unwrap(),
            job
        );
        assert_eq!(io.write_count(), 3);
    }
}

#[test]
fn keychain_vault_uncertain_archive_write_is_reconciled_before_telegram_key_creation() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(b"RTRCTV1\x010123456789abcdef0123456789abcdef");
    io.0.lock().unwrap().fail_readback = true;
    assert!(cache.archive_key(&mut io).is_err());
    let key = persisted_content_key(&io);
    let original = io.persisted().unwrap();
    for account in ["tdlib-database", "encrypted-job-store"] {
        assert!(cache.named_key(&mut io, account).is_err());
    }
    assert_eq!(io.write_count(), 1);
    assert_eq!(io.persisted().unwrap(), original);
    {
        let mut storage = io.0.lock().unwrap();
        storage.deny_reads = false;
        storage.fail_readback = false;
    }
    let tdlib = cache.named_key(&mut io, "tdlib-database").unwrap();
    assert_eq!(persisted_content_key(&io), key);
    let decoded = decode_secret_vault(&io.persisted().unwrap()).unwrap();
    assert_eq!(decoded.tdlib_database_key, Some(tdlib));
    assert_eq!(cache.archive_key(&mut io).unwrap(), key);
    assert_eq!(io.write_count(), 2);
}

#[test]
fn keychain_vault_missing_item_after_uncertain_write_blocks_mutations() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(V1_ALL);
    io.0.lock().unwrap().commit_then_error = true;
    assert!(cache.archive_key(&mut io).is_err());
    io.0.lock().unwrap().items.remove(VAULT_ACCOUNT);
    assert!(cache.archive_key(&mut io).is_err());
    assert!(
        cache
            .save_api_hash(&mut io, "0123456789abcdef0123456789abcdef")
            .is_err()
    );
    assert_telegram_secrets(&cache, &mut io);
    assert!(io.persisted().is_none());
    assert_eq!(io.write_count(), 1);
}

#[test]
fn keychain_vault_reconciliation_rejects_loss_of_an_already_published_archive_key() {
    let cache = VaultCache::default();
    let mut io = MemoryVaultIo::from_bytes(&fixture_v2());
    assert_eq!(cache.archive_key(&mut io).unwrap(), [b'C'; 32]);
    io.0.lock().unwrap().reject_write = true;
    assert!(
        cache
            .save_api_hash(&mut io, "abcdef0123456789abcdef0123456789")
            .is_err()
    );
    io.0.lock()
        .unwrap()
        .items
        .insert(VAULT_ACCOUNT.into(), V1_ALL.to_vec());
    io.0.lock().unwrap().reject_write = false;
    assert!(cache.archive_key(&mut io).is_err());
    assert!(
        cache
            .save_api_hash(&mut io, "abcdef0123456789abcdef0123456789")
            .is_err()
    );
    assert_eq!(io.persisted().unwrap(), V1_ALL);
    assert_eq!(io.write_count(), 0);
}

#[test]
fn keychain_vault_unavailable_vault_or_legacy_items_do_not_generate_replacements() {
    for account in [
        VAULT_ACCOUNT,
        "telegram-api-hash",
        "tdlib-database",
        "encrypted-job-store",
    ] {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::default();
        io.0.lock().unwrap().unavailable_account = Some(account.into());
        assert!(cache.archive_key(&mut io).is_err());
        let reads = io.read_count();
        io.0.lock().unwrap().unavailable_account = None;
        assert!(cache.named_key(&mut io, "tdlib-database").is_err());
        assert!(cache.api_hash(&mut io).is_err());
        assert_eq!(io.read_count(), reads);
        assert_eq!(io.write_count(), 0);
        assert!(io.persisted().is_none());
    }
}

#[test]
fn keychain_vault_malformed_legacy_items_are_preserved_and_failure_is_cached() {
    for account in ["telegram-api-hash", "tdlib-database", "encrypted-job-store"] {
        for value in [vec![], vec![0x11; 31], vec![0x11; 33]] {
            let cache = VaultCache::default();
            let mut io = MemoryVaultIo::default();
            io.0.lock()
                .unwrap()
                .items
                .insert(account.into(), value.clone());
            assert!(cache.archive_key(&mut io).is_err());
            let reads = io.read_count();
            assert!(cache.api_hash(&mut io).is_err());
            assert_eq!(io.read_count(), reads);
            assert_eq!(io.write_count(), 0);
            assert_eq!(io.0.lock().unwrap().items.get(account), Some(&value));
        }
    }
    for value in [vec![b'z'; 32], vec![255; 32]] {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::default();
        io.0.lock()
            .unwrap()
            .items
            .insert("telegram-api-hash".into(), value);
        assert!(cache.archive_key(&mut io).is_err());
        assert_eq!(io.write_count(), 0);
    }
}

#[test]
fn keychain_vault_failed_legacy_migration_never_publishes_or_retries_on_startup() {
    for readback_failure in [false, true] {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::default();
        {
            let mut storage = io.0.lock().unwrap();
            storage
                .items
                .insert("tdlib-database".into(), vec![b'*'; 32]);
            storage.reject_write = !readback_failure;
            storage.fail_readback = readback_failure;
        }
        assert!(cache.named_key(&mut io, "tdlib-database").is_err());
        let reads = io.read_count();
        assert!(cache.archive_key(&mut io).is_err());
        assert_eq!(io.read_count(), reads);
        assert_eq!(io.write_count(), usize::from(readback_failure));
        assert_eq!(
            io.0.lock().unwrap().items.get("tdlib-database"),
            Some(&vec![b'*'; 32])
        );
    }
}

#[test]
fn keychain_vault_invalid_api_edits_do_not_read_or_mutate_vault() {
    for hash in ["", "short", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"] {
        let cache = VaultCache::default();
        let mut io = MemoryVaultIo::from_bytes(V1_ALL);
        assert!(cache.save_api_hash(&mut io, hash).is_err());
        assert_eq!(io.read_count(), 0);
        assert_eq!(io.write_count(), 0);
        assert_eq!(io.persisted().unwrap(), V1_ALL);
    }
}
